---
- name: Maintenance 
  become: true
  become_user: "{{ postgres_system_user }}"
  tags: postgres_objects,postgres_ext
  community.postgresql.:
    ca_cert: "{{ item.ca_cert | default(omit) }}"
    cascade: "{{ item.cascade | default(omit) }}"
    comment: "{{ item.comment | default(omit) }}"
    connect_params: "{{ item.connect_params | default(omit) }}"
    db: "{{ item. db }}"
    login_host: "{{ item.login_host | default(omit) }}"
    login_password: "{{ item.login_password | default(omit) }}"
    login_unix_socket: "{{ item.login_unix_socket | default(omit) }}"
    login_user: "{{ item.login_user | default(omit) }}"
    session_role: "{{ item.session_role | default(omit) }}"
    name: "{{ item.name }}"
    port: "{{ item.port | default(omit) }}"
    schema: "{{ item.schema | default(omit) }}"
    session_role: "{{ item.session_role | default(omit) }}"
    ssl_cert: "{{ item.ssl_cert | default(omit) }}"
    ssl_key: "{{ item.ssl_key | default(omit) }}"
    state: "{{ item.state | default('present') }}"
    trust_input: "{{ item.trust_input | default(omit) }}"
    version: "{{ item.version | default(omit) }}"
  loop: "{{ postgres_exts }}
