---
- name: Maintenance 
  become: true
  become_user: "{{ postgres_system_user }}"
  tags: postgres_objects,postgres_tablespaces
  community.postgresql.:
    ca_cert: "{{ item.ca_cert | default(omit) }}"
    comment: "{{ item.comment | default(omit) }}"
    connect_params: "{{ item.connect_params | default(omit) }}"
    db: "{{ item.db | default(omit) }}"
    location: "{{ item.location | default(omit) }}"
    login_host: "{{ item.login_host | default(omit) }}"
    login_password: "{{ item.login_password | default(omit) }}"
    login_unix_socket: "{{ item.login_unix_socket | default(omit) }}"
    login_user: "{{ item.login_user | default(omit) }}"
    owner: "{{ item.owner | default(omit) }}"
    port: "{{ item.port | default(omit) }}"
    rename_to: "{{ item.rename_to | default(omit) }}"
    session_role: "{{ item.session_role | default(omit) }}"
    set: "{{ item.set | default(omit) }}"
    ssl_cert: "{{ item.ssl_cert | default(omit) }}"
    ssl_key: "{{ item.ssl_key | default(omit) }}"
    state: "{{ item.state | default('present') }}"
    ssl_mode: "{{ item.ssl_mode | default(omit) }}"
# Name of the tablespace must be defined
    tablespace: "{{ item.tablespace }}"
    trust_input: "{{ item.trust_input | default(omit) }}"
  loop: "{{ postgres_tablespaces }}
