---
- name: Maintenance subscription
  become: true
  become_user: "{{ postgres_system_user }}"
  tags: postgres_objects,postgres_subscriptions
  community.postgresql.postgresql_subscription:
    ca_cert: "{{ item.ca_cert | default(omit) }}"
    cascade: "{{ item.cascade | default(omit) }}"
    comment: "{{ item.comment | default(omit) }}"
    connect_params: "{{ item.connect_params | default(omit) }}"
    connparams: "{{ item.connparams | default(omit) }}"
# Database name must be defined
    db: "{{ item.db }}"
    login_host: "{{ item.login_host | default(omit) }}"
    login_password: "{{ item.login_password | default(omit) }}"
    login_unix_socket: "{{ item.login_unix_socket | default(omit) }}"
    login_user: "{{ item.login_user | default(omit) }}"
# Name of the subscription must be defined
    name: "{{ item.name }}"
    owner: "{{ item.owner | default(omit) }}"
    port: "{{ item.port | default(omit) }}"
    publications: "{{ item.publications | default(omit) }}"
    session_role: "{{ item.session_role | default(omit) }}"
    ssl_cert: "{{ item.ssl_cert | default(omit) }}"
    ssl_key: "{{ item.ssl_key | default(omit) }}"
    state: "{{ item.state | default('present') }}"
    ssl_mode: "{{ item.ssl_mode | default(omit) }}"
    subsparams: "{{ item.subsparams | default(omit) }}"
    trust_input: "{{ item.trust_input | default(omit) }}"
  loop: "{{ postgres_subscription }}"
