---
# 
- name: Copy data between a file/program and a PostgreSQL table
  become: true
  become_user: "{{ postgres_system_user }}"
  tags: postgres_objects,postgres_copy
  community.postgresql.:
    ca_cert: "{{ item.ca_cert | default(omit) }}"
    columns: 
    connect_params: "{{ item.connect_params | default(omit) }}"
    copy_from: 
    copy_to:
    db:
    dst:
    login_host: "{{ item.login_host | default(omit) }}"
    login_password: "{{ item.login_password | default(omit) }}"
    login_unix_socket: "{{ item.login_unix_socket | default(omit) }}"
    login_user: "{{ item.login_user | default(omit) }}"
    options:
    port:
    program: 
    session_role: "{{ item.session_role | default(omit) }}"
    src: 
    ssl_cert: "{{ item.ssl_cert | default(omit) }}"
    ssl_key: "{{ item.ssl_key | default(omit) }}"
    ssl_mode: 
    trust_input: "{{ item.trust_input | default(omit) }}"
  loop: "{{ postgres_copy_objs }}
