---
- name: Maintenance indexes
  become: true
  become_user: "{{ postgres_system_user }}"
  tags: postgres_objects,postgres_idx
  community.postgresql.postgresql_idx:
# Connect and common parameters
    ca_cert: "{{ item.0.ca_cert | default(omit) }}"
    connect_params: "{{ item.0.connect_params | default(omit) }}"
# DB Name must be defined
    db: "{{ item.0.name }}"
    login_host: "{{ item.0.login_host | default(omit) }}"
    login_password: "{{ item.0.login_password | default(omit) }}"
    login_unix_socket: "{{ item.0.login_unix_socket | default(omit) }}"
    login_user: "{{ item.0.login_user | default(omit) }}"
    port: "{{ item.0.port | default(omit) }}"
    session_role: "{{ item.0.session_role | default(omit) }}"
    ssl_cert: "{{ item.0.ssl_cert | default(omit) }}"
    ssl_key: "{{ item.0.ssl_key | default(omit) }}"
    ssl_mode: "{{ item.0.ssl_mode | default(omit) }}"
# Index parameters
    cascade: "{{ item.1.cascade | default(omit) }}"
    concurrent: "{{ item.1.concurrent | default(omit) }}"
    columns: "{{ item.1.columns | default(omit) }}"
    cond: "{{ item.1.cond | default(omit) }}"
# Index name must be defined
    idxname: "{{ item.1.idxname }}"
    idxtype: "{{ item.1.idxtype | default(omit) }}"
    schema: "{{ item.1.schema | default(omit) }}"
    state: "{{ item.1.state | default('present') }}"
    storage_params: "{{ item.1.storage_params | default(omit) }}"
    table: "{{ item.1.table | default(omit) }}"
    tablespace: "{{ item.1.tablespace | default(omit) }}"
    unique: "{{ item.1.unique | default(omit) }}"
    trust_input: "{{ item.1.trust_input | default(omit) }}"
  loop: "{{ postgres_dbs | subelements('indexes', skip_missing=True) }}"
