---
- name: Maintenance sequences
  become: true
  become_user: "{{ postgres_system_user }}"
  tags: postgres_objects,postgres_sequences
  community.postgresql.postgresql_sequence:
# Connect and common parameters
    ca_cert: "{{ item.0.ca_cert | default(omit) }}"
    connect_params: "{{ item.0.connect_params | default(omit) }}"
# Database name must defined
    db: "{{ item.0.name }}"
    login_host: "{{ item.0.login_host | default(omit) }}"
    login_password: "{{ item.0.login_password | default(omit) }}"
    login_unix_socket: "{{ item.0.login_unix_socket | default(omit) }}"
    login_user: "{{ item.0.login_user | default(omit) }}"
    port: "{{ item.0.port | default(omit) }}"
    session_role: "{{ item.0.session_role | default(omit) }}"
    ssl_cert: "{{ item.0.ssl_cert | default(omit) }}"
    ssl_key: "{{ item.0.ssl_key | default(omit) }}"
    ssl_mode: "{{ item.0.ssl_mode | default(omit) }}"
# Sequence parameters
    cache: "{{ item.1.cache | default(omit) }}"
    cascade: "{{ item.1.cascade | default(omit) }}"
    cycle: "{{ item.1.cycle | default(omit) }}"
    data_type: "{{ item.1.data_type | default(omit) }}"
    increment: "{{ item.1.increment | default(omit) }}"
    maxvalue: "{{ item.1.maxvalue | default(omit) }}"
    minvalue: "{{ item.1.minvalue | default(omit) }}"
    newschema: "{{ item.1.newschema | default(omit) }}"
    owner: "{{ item.1.owner | default(omit) }}"
    rename_to: "{{ item.1.rename_to | default(omit) }}"
    schema: "{{ item.1.schema | default(omit) }}"
# Name of sequence must be defined
    sequence: "{{ item.1.sequence }}"
    start: "{{ item.1.start | default(omit) }}"
    state: "{{ item.1.state | default('present') }}"
    trust_input: "{{ item.trust_input | default(omit) }}"
  loop: "{{ postgres_dbs | subelements('sequences', skip_missing=True) }}"
