---
# Create alter and drop database
- name: Maintenance databases
  become: true
  become_user: "{{ postgres_system_user }}"
  tags: postgres_objects,postgres_db
  community.postgresql.postgresql_db:
# Connect and common parameters
    ca_cert: "{{ item.ca_cert | default(omit) }}"
    connect_params: "{{ item.connect_params | default(omit) }}"
    login_host: "{{ item.login_host | default(omit) }}"
    login_password: "{{ item.login_password | default(omit) }}"
    login_unix_socket: "{{ item.login_unix_socket | default(omit) }}"
    login_user: "{{ item.login_user | default(omit) }}"
    port: "{{ item.port | default(omit) }}"
    session_role: "{{ item.session_role | default(omit) }}"
    ssl_cert: "{{ item.ssl_cert | default(omit) }}"
    ssl_key: "{{ item.ssl_key | default(omit) }}"
# Database parameters
    comment: "{{ item.comment | default(omit) }}"
    conn_limit: "{{ item.conn_limit | default(omit) }}"
    dump_extra_args: "{{ item.dump_extra_args | default(omit) }}"
    encoding: "{{ item.encoding | default('UTF8') }}"
    force: "{{ item.force | default(omit) }}"
    icu_locale: "{{ item.icu_locale | default(omit) }}"
    lc_collate: "{{ item.lc_collate | default(omit) }}"
    lc_ctype: "{{ item.lc_ctype | default(omit) }}"
    locale_provider: "{{ item.locale_provider | default(omit) }}"
    maintenance_db: "{{ item.maintenance_db | default(omit) }}"
# Database name and database owner are mandatory parameters
# Database name
    name: "{{ item.name }}"
# Database owner
    owner: "{{ item.owner }}"
    state: "{{ item.state | default('present') }}"
    tablespace: "{{ item.tablespace | default(omit) }}"
    target: "{{ item.target | default(omit) }}"
    target_opts: "{{ item.target_opts | default(omit) }}"
    template: "{{ item.template | default('template1') }}"
    trust_input: "{{ item.trust_input | default(omit) }}"
  loop: "{{ postgres_dbs }}"
