---
- name: Maintenance Postgres privileges
  become: true
  become_user: "{{ postgres_system_user }}"
  tags: postgres_objects,postgres_privs
  community.postgresql.postgresql_privs:
# Connect and common parameters
    ca_cert: "{{ item.0.ca_cert | default(omit) }}"
    connect_params: "{{ item.0.connect_params | default(omit) }}"
    database: "{{ item.0.name }}"
    login_host: "{{ item.0.login_host | default(omit) }}"
    login_password: "{{ item.0.login_password | default(omit) }}"
    login_unix_socket: "{{ item.0.login_unix_socket | default(omit) }}"
    login_user: "{{ item.0.login_user | default(omit) }}"
    port: "{{ item.0.port | default(omit) }}"
    session_role: "{{ item.0.session_role | default(omit) }}"
    ssl_cert: "{{ item.0.ssl_cert | default(omit) }}"
    ssl_key: "{{ item.0.ssl_key | default(omit) }}"
    ssl_mode: "{{ item.0.ssl_mode | default(omit) }}"
    trust_input: "{{ item.0.trust_input | default(omit) }}"
# Privileges parameters
    fail_on_role: "{{ item.1.fail_on_role | default(omit) }}"
    grant_option: "{{ item.1.grant_option | default(omit) }}"
    objs: "{{ item.1.objs | default(omit) }}"
    privs: "{{ item.1.privs | default(omit) }}"
    roles: "{{ item.1.roles }}"
    schema: "{{ item.1.schema | default(omit) }}"
    state: "{{ item.1.state | default('present') }}"
    target_roles: "{{ item.1.target_roles | default(omit) }}"
    type: "{{ item.1.type | default(omit) }}"
  loop: "{{ postgres_dbs | subelements('postgres_privs', skip_missing=True) }}"
